local_costmap:
  global_frame: /map
  robot_base_frame: tricycle_frame
  update_frequency: 10.0
  publish_frequency: 2.0
  transform_tolerance: 2.0
  static_map: true
  rolling_window: true
  width: 40.0
  height: 40.0
  resolution: 1